### ISSUE TITLE
Live demo is currently serving HTTP Status 400.

### ISSUE THREAD

**Issue by apriendeau** [defunctzombie/tryme#12]
![screen shot 2014-05-06 at 8 05 36 pm](https://cloud.githubusercontent.com/assets/700344/2897835/ddb64a12-d58b-11e3-8f0f-1725e09de303.png)

**Comment by defunctzombie** [comment]
Yea, the live demo has been offline for a long time. I have been lazy and there hasn't been much pressure to revive it :/
